In [1]:
import math
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib.animation as animation

In [2]:
#Definiciones iniciales

#Parte espacial
#El índice espacial es jota, el cuál va de 0 a N
h=0.1
N=500

#Parte temporal
#El índices temporal es n, el cuál va de 0 a t 
s=0.1
t=1000

#Número de ciclos (entre 1 y N/4)
N_ciclos=50

#Lambda
lamb=0.4

In [3]:
#Definimos variables iniciales
ko=(2*np.pi*N_ciclos)/N

s=1/(4*ko**2)


#Potencial
V=np.zeros(N+1)
for jota in range(N+1):
    if (jota>=(2*N)/5) and (jota<=(3*N)/5):
        V[jota]=lamb*ko**2
    else:
        V[jota]=0

        
#Función de onda inicialmente        
phi=np.zeros((N+1,t), dtype=complex)
for jota in range(N+1):
    phi[jota][0]=np.exp((ko*jota)*1j)*np.exp((-8*((4*jota)-N)**2)/N**2)


    
print(ko)
print()

print(s)
print()

print(V)
print()

print(phi)
print()

#Normal inicialmente
norma = np.linalg.norm(phi, axis=0)
print(norma)

0.6283185307179586

0.6332573977646111

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.  

In [4]:
#Definimos alpha
alpha=np.zeros(N, dtype=complex)
A=1

for jota in range(N-1, -1, -1):
    A0=-2+(2j/s)-V[jota]
    alpha[jota-1]=-A/(A0+A*alpha[jota])
    

print()
print(alpha)


[0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609696j 0.12524526+0.22609696j 0.12524526+0.22609696j
 0.12524526+0.22609

In [5]:
#Definimos beta
beta=np.zeros((N,t), dtype=complex)

#Definimos chi
chi=np.zeros((N+1,t), dtype=complex)


#Empezamos el bucle que acompaña al tiempo
for n in range(t-1):
    
    for jota in range(N-1, -1, -1):
        b=(4j*phi[jota][n])/s
        A0=-2+(2j/s)-V[jota]
        beta[jota-1][n]=(b-A*beta[jota][n])/(A0+A*alpha[jota])
        
    for jota in range(N-1):
        chi[jota+1][n]=alpha[jota]*chi[jota][n]+beta[jota][n]   

    for jota in range(N+1):
        phi[jota][n+1]=chi[jota][n]-phi[jota][n]
    
    
print(beta)
print()

print(chi)
print()

print(phi)
print()



[[ 5.33406030e-04+2.23314007e-04j  2.92561374e-04-3.91758513e-05j
   8.68564423e-05-1.29783829e-05j ...  6.95783535e-03+2.43162167e-03j
   8.41734236e-03+1.73092627e-03j  0.00000000e+00+0.00000000e+00j]
 [ 3.40934467e-04+5.60787080e-04j  4.20170179e-04+3.58331353e-04j
   3.62092025e-04+1.07779451e-04j ...  1.28992216e-02+7.10058187e-04j
   1.46536175e-02-9.92104849e-04j  0.00000000e+00+0.00000000e+00j]
 [-6.08066285e-05+7.41594159e-04j  1.17637976e-04+6.62256511e-04j
   2.76157207e-04+5.05546020e-04j ...  1.70494241e-02-3.71632136e-03j
   1.73051801e-02-6.55118175e-03j  0.00000000e+00+0.00000000e+00j]
 ...
 [-2.01176995e-33-1.88222012e-31j -4.62862396e-32-2.67761254e-31j
  -1.41450619e-31-3.63851397e-31j ... -1.37015075e-01-1.53262720e-01j
  -1.75760789e-01-1.15547465e-01j  0.00000000e+00+0.00000000e+00j]
 [ 5.45054337e-32-1.16802311e-31j  1.04915026e-32-1.83420523e-31j
  -5.20581642e-32-2.31048377e-31j ... -9.20031153e-02-9.51000825e-02j
  -1.16016242e-01-6.97575830e-02j  0.00000000e+

In [6]:
norma=np.zeros((N,t))

#calculo
for n in range(t):
    suma=0
    for jota in range(N):
        suma=suma+((((abs(phi[jota,n]))**2+(abs(phi[jota+1,n]))**2)/2)*h)
        norma[jota][n]=suma
        
print(norma)  

[[1.28877007e-08 8.16048820e-09 5.92835774e-09 ... 5.79821602e-07
  8.03725736e-07 1.07315244e-06]
 [2.94992150e-08 1.76368688e-08 9.89751825e-09 ... 3.13595981e-06
  4.18656292e-06 5.50924671e-06]
 [5.08667304e-08 3.45101944e-08 2.11635607e-08 ... 9.04825445e-06
  1.10890255e-05 1.38278668e-05]
 ...
 [5.53891824e+00 5.53891824e+00 5.53891824e+00 ... 3.75151648e+00
  3.75134217e+00 3.75116042e+00]
 [5.53891824e+00 5.53891824e+00 5.53891824e+00 ... 3.75252048e+00
  3.75239297e+00 3.75225982e+00]
 [5.53891824e+00 5.53891824e+00 5.53891824e+00 ... 3.75284891e+00
  3.75273673e+00 3.75261935e+00]]


In [7]:
#Guardo las matrices y vectores en txt para verlos mejor

#alpha
np.savetxt('H:/Escritorio/Compu/Problema3/Datos/alpha.txt', alpha)

#beta
np.savetxt('H:/Escritorio/Compu/Problema3/Datos/beta.txt', beta)

#chi
np.savetxt('H:/Escritorio/Compu/Problema3/Datos/chi.txt', chi)

#phi
np.savetxt('H:/Escritorio/Compu/Problema3/Datos/phi.txt', phi)

#potencial
np.savetxt('H:/Escritorio/Compu/Problema3/Datos/pot.txt', phi)


#Datos para representar
datos=np.zeros((N+2,2))

with open('H:/Escritorio/Compu/Problema3/Datos/datos.txt', 'w') as f:
    for n in range(t):
        for jota in range(N):
            datos[jota][0]=jota
            datos[jota][1]=np.abs(phi[jota][n])**2
            
        np.savetxt(f, datos, fmt='%f', delimiter=',')
        f.write('\n')
        print(datos)    

[[0.00000000e+00 1.12535175e-07]
 [1.00000000e+00 1.45218839e-07]
 [2.00000000e+00 1.87011449e-07]
 ...
 [4.99000000e+02 6.23286974e-63]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]]
[[0.00000000e+00 1.12535175e-07]
 [1.00000000e+00 5.06745894e-08]
 [2.00000000e+00 1.38853023e-07]
 ...
 [4.99000000e+02 1.26630451e-62]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]]
[[0.00000000e+00 1.12535175e-07]
 [1.00000000e+00 6.03198007e-09]
 [2.00000000e+00 7.33512302e-08]
 ...
 [4.99000000e+02 2.10443504e-62]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]]
[[0.00000000e+00 1.12535175e-07]
 [1.00000000e+00 1.02782911e-09]
 [2.00000000e+00 1.79347214e-08]
 ...
 [4.99000000e+02 3.49246835e-62]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00]]
[[0.00000000e+00 1.12535175e-07]
 [1.00000000e+00 3.63938610e-09]
 [2.00000000e+00 1.91168474e-09]
 ...
 [4.99000000e+02 6.21161429e-62]
 [0.00000000e+00 0.00000000e+00]
 [0.00000000e+